import { Category, Post } from "@/types";

export const categories: Category[] = [
  {
    id: "korean-classic",
    name: "한국 고전 문학",
    description: "조선시대부터 근대까지, 한국 고전 문학의 명작들을 소개합니다.",
    avatar: "고전",
    followerCount: 4821,
    postCount: 142,
  },
  {
    id: "korean-modern",
    name: "한국 현대 소설",
    description: "20세기 이후 한국 현대 소설의 흐름을 따라갑니다.",
    avatar: "현대",
    followerCount: 7304,
    postCount: 218,
  },
  {
    id: "world-literature",
    name: "세계 문학",
    description: "동서양을 넘나드는 세계 문학의 걸작들.",
    avatar: "세계",
    followerCount: 9152,
    postCount: 305,
  },
  {
    id: "science",
    name: "과학 · 기술",
    description: "과학적 사고와 기술의 역사를 담은 책들.",
    avatar: "과학",
    followerCount: 3267,
    postCount: 89,
  },
  {
    id: "history",
    name: "역사 · 철학",
    description: "인류의 역사와 사상을 탐구하는 책들.",
    avatar: "역사",
    followerCount: 5640,
    postCount: 176,
  },
];

export const posts: Post[] = [
  {
    id: "1",
    categoryId: "korean-classic",
    category: categories[0],
    bookTitle: "홍길동전",
    bookAuthor: "허균",
    bookYear: 1612,
    coverColor: "#2D6A4F",
    content:
      "조선 최초의 한글 소설. 서자 출신 홍길동이 차별에 맞서 활빈당을 이끌며 이상 사회를 꿈꾸는 이야기입니다. 신분제 사회에 대한 신랄한 비판이 400년이 지난 지금도 울림을 줍니다.",
    likeCount: 1423,
    commentCount: 87,
    tags: ["고전소설", "조선", "사회비판"],
  },
  {
    id: "2",
    categoryId: "korean-modern",
    category: categories[1],
    bookTitle: "소나기",
    bookAuthor: "황순원",
    bookYear: 1952,
    coverColor: "#457B9D",
    content:
      "짧지만 강렬한 여운을 남기는 단편소설. 소년과 소녀의 순수한 감정을 소나기라는 자연 현상에 빗대어 표현한 한국 단편 문학의 정수입니다.",
    likeCount: 3201,
    commentCount: 214,
    tags: ["단편소설", "순수문학", "1950년대"],
  },
  {
    id: "3",
    categoryId: "world-literature",
    category: categories[2],
    bookTitle: "데미안",
    bookAuthor: "헤르만 헤세",
    bookYear: 1919,
    coverColor: "#6D4C41",
    content:
      "자아를 찾아가는 청년 싱클레어의 성장 이야기. '새는 알에서 나오려고 투쟁한다'는 구절은 지금도 많은 이들의 마음속에 남아 있습니다.",
    likeCount: 5872,
    commentCount: 432,
    tags: ["성장소설", "독일문학", "실존주의"],
  },
  {
    id: "4",
    categoryId: "science",
    category: categories[3],
    bookTitle: "코스모스",
    bookAuthor: "칼 세이건",
    bookYear: 1980,
    coverColor: "#1A1A2E",
    content:
      "우주의 기원부터 인류 문명의 미래까지. 칼 세이건이 펼쳐내는 광대한 우주 이야기는 과학을 시로 만들어 버립니다. 과학 교양서의 영원한 고전.",
    likeCount: 4103,
    commentCount: 298,
    tags: ["천문학", "과학교양", "우주"],
  },
  {
    id: "5",
    categoryId: "history",
    category: categories[4],
    bookTitle: "논어",
    bookAuthor: "공자",
    bookYear: -479,
    coverColor: "#7B2D00",
    content:
      "2500년 전 공자와 제자들의 대화록. 인(仁), 의(義), 예(禮)를 중심으로 한 동아시아 사상의 근간. 짧은 구절 하나하나가 오늘날에도 깊은 통찰을 줍니다.",
    likeCount: 2987,
    commentCount: 156,
    tags: ["동양철학", "유교", "고전"],
  },
  {
    id: "6",
    categoryId: "korean-classic",
    category: categories[0],
    bookTitle: "춘향전",
    bookAuthor: "작자 미상",
    bookYear: 1754,
    coverColor: "#B5338A",
    content:
      "신분을 뛰어넘는 사랑 이야기. 춘향과 이몽룡의 사랑을 통해 조선 사회의 신분 질서에 저항하는 민중의 목소리를 담았습니다. 판소리계 소설의 대표작.",
    likeCount: 2156,
    commentCount: 103,
    tags: ["판소리", "조선", "로맨스"],
  },
  {
    id: "7",
    categoryId: "korean-modern",
    category: categories[1],
    bookTitle: "난장이가 쏘아올린 작은 공",
    bookAuthor: "조세희",
    bookYear: 1978,
    coverColor: "#374151",
    content:
      "산업화 시대 소외된 이들의 이야기. 도시 재개발로 삶의 터전을 잃어가는 난장이 가족의 이야기를 통해 70년대 한국 사회의 이면을 날카롭게 포착합니다.",
    likeCount: 3844,
    commentCount: 267,
    tags: ["사회소설", "1970년대", "산업화"],
  },
  {
    id: "8",
    categoryId: "world-literature",
    category: categories[2],
    bookTitle: "백년의 고독",
    bookAuthor: "가브리엘 가르시아 마르케스",
    bookYear: 1967,
    coverColor: "#92400E",
    content:
      "마콘도라는 가상의 마을을 배경으로 한 부엔디아 가문 7대의 이야기. 마술적 사실주의의 정수로 꼽히는 작품이며 라틴아메리카 문학의 금자탑입니다.",
    likeCount: 6231,
    commentCount: 489,
    tags: ["마술적사실주의", "남미문학", "노벨문학상"],
  },
];
